### PR TITLE
hoge

### PR DESCRIPTION
**Pull request by kvnnn**
pull request comment show here

### CODE REVIEW

**Comment by yum-kvn** [comment]
hoge

**Comment by yum-kvn** [comment]
new comment here{
    NSFont = "\"Helvetica 15.00 pt. P [] (0x2eca380) fobj=0xaf61f80, spc=4.17\"";
    NSParagraphStyle = "Alignment 4, LineSpacing 0, ParagraphSpacing 0, ParagraphSpacingBefore 0, HeadIndent 0, TailIndent 0, FirstLineHeadIndent 0, LineHeight 0/0, LineHeightMultiple 0, LineBreakMode 0, Tabs (\n    28L,\n    56L,\n    84L,\n    112L,\n    140L,\n    168L,\n    196L,\n    224L,\n    252L,\n    280L,\n    308L,\n    336L\n), DefaultTabInterval 0, Blocks (null), Lists (null), BaseWritingDirection -1, HyphenationFactor 0, TighteningFactor 0.05, HeaderLevel 0";
}

**Comment by yum-kvn** [comment]
<NSTextView: 0x99743d0>
    Frame = {{0.00, 0.00}, {158.00, 123.00}}, Bounds = {{0.00, 0.00}, {158.00, 123.00}}
    Horizontally resizable: NO, Vertically resizable: YES
    MinSize = {158.00, 123.00}, MaxSize = {463.00, 10000000.00}

**Comment by yum-kvn** [comment]
add comment

**Comment by yum-kvn** [comment]
hoge

**Comment by kvnnn** [comment]
new comment 1

**Comment by kvnnn** [comment]
new comment 2

**Pull request closed without merging**
